techexpertspro/portal-ascepa

- .github/ISSUE_TEMPLATE/bug_template.md
- .github/ISSUE_TEMPLATE/improvement_template.md
- .github/pull_request_template.md
This pull request introduces new issue and pull request templates to the repository. The templates are written in Portuguese and include sections for describing the issue or pull request, expected behavior, code snippets, and other relevant observations. 
The most important changes are:
Issue templates:
* [`.github/ISSUE_TEMPLATE/bug_template.md`](diffhunk://#diff-48a6f3ad0aa7299a11cb515c6348781a5601ddf7c01e7165886b0bda36a50bebR1-R52): Added a new issue template for reporting bugs. The template includes sections for describing the bug, expected behavior, the branch where the bug is occurring, code snippets, and other relevant observations.
* [`.github/ISSUE_TEMPLATE/improvement_template.md`](diffhunk://#diff-d40e9819a90f0237e8757e292542774ff1df25b20f1076435d594f657694e88bR1-R28): Added a …
> chore: add pull request and issue templates

- .vscode/extensions.json
This pull request includes changes to the `.vscode/extensions.json` file. The changes involve the addition of two new extensions, `"angular.ng-template"` and `"dbaeumer.vscode-eslint"`, to the list of recommended extensions. 
These changes will help improve the development environment by providing additional tools for Angular and ESLint.
---
feat: Uma nova funcionalidade
---
---
---
> chore: add vscode extensions recommendations

- .github/actions/cached-deps/action.yml
- .github/workflows/ci.yml
- package-lock.json
This pull request introduces significant changes to the GitHub Actions workflow. It adds a new custom GitHub Action for caching dependencies and modifies the continuous integration (CI) workflow to use this new action. The changes aim to optimize the CI process by caching dependencies, which can significantly reduce the time it takes to run the workflow.
Here are the most important changes:
GitHub Actions:
* [`.github/actions/cached-deps/action.yml`](diffhunk://#diff-aab0476025ac71df34a9d337ab41f3db6d51680817f139c0ccc6f8ab343486edR1-R28): A new custom GitHub Action has been added. This action is designed to fetch and cache the project's dependencies. It uses npm to fetch the dependencies, and the `actions/cache@v3` action to cache them. The action has an input parameter `caching` that …
> ci: add workflow

- .eslintrc.json
- .prettierrc
- .vscode/settings.json
- e2e/src/support/commands.ts
- src/main.ts
This pull request primarily focuses on improving the code quality and readability by enforcing stricter linting rules and formatting standards across the project. The most significant changes include the addition of new ESLint rules, the introduction of new Prettier formatting rules, and the setting up of default code formatting settings in Visual Studio Code.
Linting improvements:
* [`.eslintrc.json`](diffhunk://#diff-6884918dc8291219be508e05e28965b958c734def85324f3b53858ea4702090fR19-R20): Added new ESLint rules to prevent the use of `console` statements and the explicit use of `any` type in TypeScript. These rules will help to maintain the code quality and prevent potential bugs.
Code formatting enhancements:
* [`.prettierrc`](diffhunk://#diff-663ade211b3a1552162de21c4031fcd16be99407aae …
> chore: add prettier and eslint rules

- jest.preset.js
This pull request introduces a change to the `jest.preset.js` file. The change sets a coverage threshold for the test suite, ensuring that at least 50% of branches, functions, lines, and statements are covered by tests. This is a step towards enforcing code quality and robustness by encouraging comprehensive testing.
---
chore: Outras alterações que não modificam os arquivos de origem ou de teste
---
---
---
> chore: setup test coverage

- CONTRIBUTING.md
Creation of contribuiting.md document, that includes the path to fork the project, create standardized branchs and commits, and some other patterns.
---
docs: Apenas mudança de documentação
---
> docs: Create CONTRIBUTING.md #27

- LICENSE
LICENSE document created, which includes permissions to use and distribute the software.
LICENSE document created, of type MIT
> docs: Create LICENSE document 

- docs/CONTRIBUTING.md
- docs/LICENSE.md
- docs/SECURITY.md
Houve a diferença de formatação entre MIT License (como está fora de formatação) e outros que estão bem formatado
---
doc: Documentos traduzidos para inglês com arquivos SECURITY.MD e CONTRIBUTING.md e formatação no arquivo LICENSE.md
---
---
---
> Translate SECURITY.md file to english

- .github/workflows/ci.yml
- .github/workflows/sonarcloud-scan.yml
- sonar-project.properties
- src/app/app.component.html
- src/app/app.component.spec.ts
- src/app/app.component.ts
feat/ci: Adicionado a execução do SonarCloud no setup da pipeline, para análise do código, scaner e identificar code's smells.
Projeto Mentoria Angular PRO | Tech Experts: https://sonarcloud.io/organizations/techexpertspro/projects
https://sonarcloud.io/project/overview?id=portal-ascepa
---
feat/ci: Add SonarCloud a pipeline do GitActions
---
---
Não há
---
> ci: add sonarcloud

- modules/shared-ui/.eslintrc.json
- modules/shared-ui/README.md
- modules/shared-ui/jest.config.ts
- modules/shared-ui/project.json
- modules/shared-ui/src/test-setup.ts
- modules/shared-ui/tsconfig.json
- modules/shared-ui/tsconfig.lib.json
- modules/shared-ui/tsconfig.spec.json
- tsconfig.base.json
---
feat: add shared ui module
---
---
---
> feat: add shared ui module

- modules/home/.eslintrc.json
- modules/home/README.md
- modules/home/jest.config.ts
- modules/home/project.json
- modules/home/src/index.ts
- modules/home/src/lib/home/home.component.html
- modules/home/src/lib/home/home.component.spec.ts
- modules/home/src/lib/home/home.component.ts
- modules/home/src/test-setup.ts
- modules/home/tsconfig.json
- modules/home/tsconfig.lib.json
- modules/home/tsconfig.spec.json
- tsconfig.base.json
Para melhorar a separação de responsabilidades e otimizar a performance do CI/CD, foi criado o módulo 'home' da aplicação.
- Gerada lib 'home' utilizando o Generator: `npx nx generate @portal-ascepa/angular-plugin:module --name=home`
- Criado componente 'HomePage' (sem implementação inicial)
- Adicionada breve descrição no arquivo README.md da nova lib
---
feat: criar módulo home
---
---
Não se aplica.
---
> feat(home): add lib and component (#88)

- .lintstagedrc
Related to #109 
This pull request includes a modification to the `.lintstagedrc` file. The change narrows the types of files that will trigger the linting, testing, and formatting scripts. Specifically, `json`, `css`, and `scss` files have been removed from the list. This means that changes to these file types will no longer automatically trigger these scripts.
---
fix: Correção de algum bug
---
---
---
> fix: remove extensions from lint-staged

- src/scss/_global.scss
- src/scss/components/_index.scss
- src/scss/components/typography/_mixin.scss
- src/scss/components/typography/_styles.scss
- src/scss/tokens/_index.scss
- src/scss/tokens/typography/_token.scss
Aplicar configurações padrões do Styleguide no SCSS
style: add typography
> style: add typography

- .stylelintrc.json
- package-lock.json
- package.json
Incluindo configuração especifica aos arquivos de estilos, para que as regras de validações sejam especificar para este tipo de arquivo.
---
fix: Ajustando as validações do tipo scss
---
---
> bugfix: include configuration to apply specify rules to style files

- cypress.config.ts
- e2e/cypress.config.ts
- e2e/src/e2e/Accessing-Portal.cy.ts
- e2e/src/e2e/app.cy.ts
- e2e/src/support/app.po.ts
Correção e implementação dos Testes E2E com Cypress.
Documentação criada relacionado aos Testes E2E com Cypress: https://github.com/techexpertspro/portal-ascepa/wiki/Cypress-%E2%80%90-Teste-E2E-(End%E2%80%90to%E2%80%90End)
---
test: Adicionando testes ausentes ou corrigindo testes existentes. (**Corrigindo os testes iniciais E2E e implementando um case test**).
---
- [ X ] Revi meu próprio código antes de enviar para revisão
- [ X ] Testei minha correção ou recurso extensivamente antes de enviar para revisão
- [ X ] Formatei meu código usando o guia de estilo de interface (Prettier + ESLint)
- [ X ] Meu código está bem documentado com apenas informações relevantes
- [ X ] Minhas alterações não geram novos avisos
- [ X ] Meus commits são bem organizados, descritivos e fáceis de reverter
- …
> test(Cypress): Correction/Implementation of E2E Tests.

- README.md
Foram ajustados os links da seção "Como contribuir" e  "Conecte-se conosco"  do README.md.
> fix(docs): ajuste nos links do readme.md

- modules/layout/src/index.ts
- modules/layout/src/lib/header/header.component.html
- modules/layout/src/lib/header/header.component.scss
- modules/layout/src/lib/header/header.component.spec.ts
- modules/layout/src/lib/header/header.component.ts
- src/app/app.component.html
- src/app/app.component.ts
- src/scss/tokens/_index.scss
- src/scss/tokens/colors/_token.scss
- src/scss/tokens/generic/_mixin.scss
- src/scss/tokens/generic/_token.scss
- src/styles.scss
- Criação do componente Header com layouts para Web e Mobile(responsivo)
- Criado novos mixins para padronizar **tamanho de borda** e **mixins** para adicionar **efeito de transição suave** para hover em botões ou em outros elementos
- `src/scss/tokens/generic/_mixin.scss`
- `src/scss/tokens/generic/_token.scss`
- Adicionado propriedade `box-sizing: border-box` em `src/styles.scss` a todos os componentes para prevenir problemas de dimensão padrão dos componentes
- Alteração da fonte padrão dos elementos do `body` para uma variável que já possuía o valor
---
Menu desktop:
Menu mobile fechado:
Menu mobile aberto:
feat: Uma nova funcionalidade
---
---
- Já deixamos o componente Header adicionado em `app.component.html` no local onde imaginamos que ele será colocado
- Os links do Header estão …
> feat: create header component

- src/app/app.routes.ts
---
perf: Ajuste no titulo da Pagina
---
---
Mudança de titulo na Pagina para seu nome por extenso e não somente sua abreviação. Apoiando no SEO e acessibilidade de leitores de tela.
> perf(title): rename title of the main page

- modules/home/src/lib/home/home.component.spec.ts
- modules/home/src/lib/home/home.component.ts
- src/index.html
Implementado [SEO] Adicionado Meta Tags para o Portal Ascepa. As meta tags são uma parte essencial da otimização para motores de busca (SEO). Elas ajudam a comunicar aos mecanismos de busca o conteúdo das suas páginas e melhorar o ranqueamento.
Portal Ascepa antes de adicionar Meta Tags:
Portal Ascepa depois de adicionar Meta Tags:
---
feat: Uma nova funcionalidade. **[SEO] Adicionar Meta Tags para as Pages .**
---
---
Teste de Mesa:
---
> Feat/[SEO] Adicionar Meta Tags para as Pages

- jest.config.app.ts
- modules/shared-ui/jest.config.ts
Remoção de warnings do Jest
fix: Correção de algum bug
> :bug: fix(config): remove warnings

- modules/home/src/lib/about-us/about-us.component.html
- modules/home/src/lib/about-us/about-us.component.scss
- modules/home/src/lib/home/home.component.ts
Implement responsive design for the About Us section to improve user experience across different device sizes.
Componente Desktop:
Componente mobile:
---
style: implement responsive design for about-us section
---
---
---
> styles(about-us): implement responsive design for about-us section
